import Head from "next/head";

import Header from "../components/Header";

export default function Home() {
    return (
        <div className="h-full min-h-screen bg-gray-200 ">
            <Head>
                <title>Pocketlingo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <span className="px-3 text-gray-600 text-sm">
                Welcome, select a chapter...
            </span>
        </div>
    );
}
